openapi: "3.0.0"
info:
  title: "TODO List API"
  description: "A simple API to manage a TODO list."
  version: "1.0.0"

paths:
  /todos:
    get:
      summary: "Retrieve all TODOs"
      responses:
        '200':
          description: "A list of TODO items."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    task:
                      type: string
    post:
      summary: "Create a new TODO"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
      responses:
        '201':
          description: "TODO item created successfully."
  /todos/{id}:
    get:
      summary: "Retrieve a TODO item by ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "A single TODO item."
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  task:
                    type: string
        '404':
          description: "TODO item not found."
    delete:
      summary: "Delete a TODO item by ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: "TODO item deleted successfully."